# fly.toml app configuration file generated for gmspace-chat on 2024-10-18T11:45:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gmspace-chat'
primary_region = 'cdg'

[build]

[[services]]
    internal_port = 2929
    protocol = 'tcp'

  [[services.ports]]
      handlers = ["tls", "http"]
      port = 2929
[[services]]
    internal_port = 2939
    protocol = 'tcp'

  [[services.ports]]
      handlers = ["tls", "http"]
      port = 2939

[[services]]
    internal_port = 2939
    protocol = 'tcp'

  [[services.ports]]
      handlers = ["tls", "http"]
      port = 2939

[[services]]
    internal_port = 3000
    protocol = 'tcp'

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
[[vm]]
  size = 'shared-cpu-1x'
